### ISSUE TITLE
bash: texrecon: command not found

### ISSUE THREAD

**Issue by ZhenWusi** [GAP-LAB-CUHK-SZ/gaustudio#10]
when i run `texrecon ./images ./fused_mesh.ply ./results/textured_mesh --outlier_removal=gauss_clamping --data_term=area --no_intermediate_results` happen that bash: texrecon: command not found
<img width="701" alt="3" src="https://github.com/GAP-LAB-CUHK-SZ/gaustudio/assets/105499590/fc2b8255-4e70-499b-b563-35186be8e3b2">

and i had run 
`git clone https://github.com/nmoehrle/mvs-texturing.git
cd mvs-texturing
mkdir build && cd build && cmake ..
make (or make -j for parallel compilation)`

**Comment by hugoycj** [comment]
It seems that the `texrecon` command is not found in your system's PATH environment variable.  To resolve this issue, you need to add the directory containing the `texrecon` executable to your system's PATH environment variable. Here's how you can do it:

1. Locate the directory where the `texrecon` executable is installed. If you followed the instructions you provided (`git clone https://github.com/nmoehrle/mvs-texturing.git` and `make` in the `build` directory), the `texrecon` executable should be in the `build/bin` directory of the `mvs-texturing` repository.

2. Open your terminal and navigate to the `mvs-texturing` repository.

3. Run the following command to add the `build/bin` directory to your PATH environment variable (this is a temporary change for the current terminal session):

   ```
   export PATH=$PATH:$(pwd)/build/bin
   ```

   Replace `$(pwd)` with the full path to the `mvs-texturing` repository if you're not currently in that directory.

4. After running the above command, you should be able to run `texrecon` from any directory in the current terminal session.

Alternatively, you can permanently add the `build/bin` directory to your system's PATH environment variable by modifying your shell's configuration file (e.g., `.bashrc` for Bash, `.zshrc` for Zsh). Consult your shell's documentation for instructions on how to do this.

Once you've added the directory containing the `texrecon` executable to your PATH environment variable, you should be able to run the command without encountering the "command not found" error.

**Comment by xBeho1der** [comment]
Hi! @DYH200009 

If you compile mvs-texturing successfully, maybe you can try finding `texrecon` in `mvs-texturing/build/apps/texrecon` directory.

**Comment by DYH200009** [comment]
感谢大佬指路，补充一下，添加路径的时候指令为export PATH=$PATH:$(pwd)/build/apps/texrecon
