### ISSUE TITLE
Questions on params-based input data

### ISSUE THREAD

**Issue by Ramseyous0109** [GAP-LAB-CUHK-SZ/gaustudio#14]
Hi, it's an amazing work for gaussian splatting research.

It seems the input data format for mesh extraction is based on vanilla gaussian splatting with a `.ply` file.

I wonder if I want to use param-based output data from some 3dgs algorithms (eg. [splatam](https://github.com/spla-tam/SplaTAM)), whose output is a set of 3dgs params:

```
    params = {
        'means3D'
        'rgb_colors'
        'unnorm_rotations'
        'logit_opacities'
        'log_scales'
    }
```

how to modify the scripts.

**Comment by Jiahao620** [comment]
Hi, I think you should process these output files from other 3dgs algorithms first, i.e. convert these output files to the standard form as original gs. For your example above,
```
params = {
        'means3D' -----> 'xyz' 
        'rgb_colors' -----> 'f_dc', 'f_rest'
        'unnorm_rotations' -----> 'rotation'
        'logit_opacities' -----> 'opacity'
        'log_scales' -----> 'scaling'
    }  
````
Noted that 'f_dc' is converted from rgb and 'f_rest' is set to 0.

**Comment by Ramseyous0109** [comment]
Thanks! I actually follow these steps to successfully generate point_cloud.ply file.
