### ISSUE TITLE
Mesh extraction takes too long.

### ISSUE THREAD

**Issue by JuliusQv** [GAP-LAB-CUHK-SZ/gaustudio#2]
Thanks for your amazing work.
i use the following command to extract the mesh:
`gs-extract-mesh -m ./data/1750250955326095360_data/result -o ./output/1750250955326095360_data`

but it takes too long:
![image](https://github.com/GAP-LAB-CUHK-SZ/gaustudio/assets/55577869/c8d3fc99-f694-4b8b-83de-c64ada6fac9e)

Is there any solution?

**Comment by hugoycj** [comment]
Sorry to bother, we currently set a small voxel size for extract details. For fast mesh extraction and to avoid overhead processing and memory usage, you could try tuning the parameters of vdbfusion [here](https://github.com/GAP-LAB-CUHK-SZ/gaustudio/blob/master/gaustudio/scripts/extract_mesh.py#L81) to:
```
vdb_volume = vdbfusion.VDBVolume(voxel_size=0.2, sdf_trunc=0.8, space_carving=False)  # For Large Scene
```

**Comment by hugoycj** [comment]
If you are training with high-resolution images, such as 4K images, it is recommended to lower the resolution when using the gs-extract-mesh command for mesh extraction. You can do this by adding the -r parameter followed by a scaling factor. For example:
```
gs-extract-mesh -r 4 ...
```

**Comment by JuliusQv** [comment]
Thank you for your help. It's very useful.

But the mesh I got is empty, and all saved mask images are empty, too.

I am very confused Why is the rendering depth greater than 10 useful in [here](https://github.com/GAP-LAB-CUHK-SZ/gaustudio/blob/3cef07c4274a3be2818dd6172f6642f3112f77ad/gaustudio/scripts/extract_mesh.py#L99)

`invalid_mask = rendered_depth > 10.`

**Comment by Tao-11-chen** [comment]
It depends on your scene coordinate actually, set it to a larger value may helpful for large scale scenes.

**Comment by LaFeuilleMorte** [comment]
you can set VDBVolume(... , space_carving = False) for object-centric case
