### ISSUE TITLE
the structure of camera json file

### ISSUE THREAD

**Issue by GONGJIA0208** [GAP-LAB-CUHK-SZ/gaustudio#20]
Could you show an example of cameras.json file? I want to transfer a gaussian model to mesh but have no idea on how to build the cameras.json.

**Comment by GONGJIA0208** [comment]
solved.

**Comment by JaLnYn** [comment]
Hi, I was wondering how you solved this? what is cameras.json?

**Comment by bolopenguin** [comment]
How did you solve?
