### ISSUE TITLE
About DTU dataset

### ISSUE THREAD

**Issue by Yifever20002** [GAP-LAB-CUHK-SZ/gaustudio#26]
Thanks for your great work!
How can I train 3dgs with the DTU dataset, will you support this in the future?

**Comment by hugoycj** [comment]
We have already added support to reconstruction datasets such as DTU, BlendedMVS, and MobileBrick. The demo usage will be released soon in [2dgs-gaustudio](https://github.com/hugoycj/2dgs-gaustudio). You could check back later this week
