### ISSUE TITLE
SuGaR results in the GauStudio paper

### ISSUE THREAD

**Issue by Cenbylin** [GAP-LAB-CUHK-SZ/gaustudio#33]
Thanks for the impressive work!

For comparison purpose, I would like to ask how the SuGaR's results (Fig. 4 in your paper) for Blender dataset were obtained.

As the official code of SuGaR didn't provide such adaption (espetially dataloader and training settings), may I ask you for the implementation details?  It would be greatly appreciated, if these codes can be shared.

**Comment by hugoycj** [comment]
Thank you for your interest! We have provided the processed dataset in the Colmap format for evaluation.  https://cuhko365-my.sharepoint.com/:f:/g/personal/118010378_link_cuhk_edu_cn/En7TRlmsyTtMor40XQlUswMBLy63gqItvrV5z0gRiiXjOg?e=mggVpx

To visualize the results in the same format as the paper, we have provided a render script. You can run the following command:

```
gs-render-mesh -m <mesh path> -s <colmap dir> -o <output dir>
```

Replace `<mesh path>` with the path to your output mesh file, `<colmap dir>` with the directory containing your Colmap data, and `<output dir>` with the desired output directory for the rendered images.

**Comment by Cenbylin** [comment]
thanks!
