### ISSUE TITLE
ModuleNotFoundError: No module named 'diff_surfel_rasterization'

### ISSUE THREAD

**Issue by Neal2020GitHub** [GAP-LAB-CUHK-SZ/gaustudio#37]
Hi authors!

I encountered this issue when running `gs-extract-mesh`. Any solutions to this?

**Comment by hugoycj** [comment]
Apologies for the trouble. We've recently added the 2dgs's surfel rasterizer (available at https://github.com/hbb1/diff-surfel-rasterization.git) to our framework. However, this requires an additional installation step to set up their library. 

We understand the inconvenience and will fix it soon by making the installation of this library optional.
