### ISSUE TITLE
Will the full training code be released?

### ISSUE THREAD

**Issue by warmsnow-sh** [GAP-LAB-CUHK-SZ/gaustudio#40]
The vision of this project is very exciting, and the creation of a modular Gaussian pipeline may simplify the whole process, but it seems that this will require more time for maintainers.
The previous expected release time was early May, but now May is almost past lol,close to forgot about this project

**Comment by hugoycj** [comment]
Sorry for the delay in the release. I have been occupied with [another project](https://github.com/hugoycj/2.5d-gaussian-splatting) recently and preparing [all the dataset loaders](https://github.com/GAP-LAB-CUHK-SZ/gaustudio/tree/master/gaustudio/datasets). These tasks have taken more time than I expected. 

I will complete the release of initialization this week, including skybox initialization, mesh initialization, and MVSplat initialization (in a similar manner to the recent MVSGaussian). The release of the entire pipeline should be delayed until around the end of June, before the ECCV decision.
