### ISSUE TITLE
Will neusg be supported in the future?

### ISSUE THREAD

**Issue by nangongliufeng** [GAP-LAB-CUHK-SZ/gaustudio#5]
https://arxiv.org/abs/2312.00846

**Comment by hugoycj** [comment]
@nangongliufeng We  have a customized version of Neuralangelo (https://github.com/hugoycj/Instant-angelo) that utilizes the multi-view stereo (MVS) point cloud to improve the reconstruction. It's feasible that you could try integrating the point cloud generated by GAUStudio into this library to get similar results as Neusg.
