### ISSUE TITLE
texrecon /images /renders/iteration_7000/fused_mesh.ply ./results/textured_mesh --outlier_removal=gauss_clamping --data_term=area --no_intermediate_results texrecon (built on Mar 21 2024, 21:02:27) Load and prepare mesh:  PLY Loader: comment https://github.com/mikedh/trimesh Reading PLY: 71353 verts... 134136 faces... done. Generating texture views:  No proper input scene descriptor given. A input descriptor can be: BUNDLE_FILE - a bundle file (currently onle .nvm files are supported) SCENE_FOLDER - a folder containing images and .cam files MVE_SCENE::EMBEDDING - a mve scene and embedding

### ISSUE THREAD

**Issue by sunshineywz123** [GAP-LAB-CUHK-SZ/gaustudio#7]
texrecon /images /renders/iteration_7000/fused_mesh.ply ./results/textured_mesh --outlier_removal=gauss_clamping --data_term=area --no_intermediate_results texrecon (built on Mar 21 2024, 21:02:27) Load and prepare mesh:  PLY Loader: comment https://github.com/mikedh/trimesh Reading PLY: 71353 verts... 134136 faces... done. Generating texture views:  No proper input scene descriptor given. A input descriptor can be: BUNDLE_FILE - a bundle file (currently onle .nvm files are supported) SCENE_FOLDER - a folder containing images and .cam files MVE_SCENE::EMBEDDING - a mve scene and embedding

ls images
100.png  114.png  128.png  141.png  155.png  169.png  182.png  196.png  209.png  222.png  236.png  24.png   263.png  277.png  290.png  303.png  317.png  330.png  344.png  358.png  371.png  385.png  399.png  411.png  51.png  65.png  79.png  92.png
101.png  115.png  129.png  142.png  156.png  16.png   183.png  197.png  20.png   223.png  237.png  250.png  264.png  278.png  291.png  304.png  318.png  331.png  345.png  359.png  372.png  386.png  39.png   412.png  52.png  66.png  7.png   93.png
102.png  116.png  12.png   143.png  157.png  170.png  184.png  198.png  210.png  224.png  238.png  251.png  265.png  279.png  292.png  305.png  319.png  332.png  346.png  35.png   373.png  387.png  3.png    413.png  53.png  67.png  80.png  94.png
103.png  117.png  130.png  144.png  158.png  171.png  185.png  199.png  211.png  225.png  239.png  252.png  266.png  27.png   293.png  306.png  31.png   333.png  347.png  360.png  374.png  388.png  400.png  414.png  54.png  68.png  81.png  95.png
104.png  118.png  131.png  145.png  159.png  172.png  186.png  19.png   212.png  226.png  23.png   253.png  267.png  280.png  294.png  307.png  32

**Comment by hugoycj** [comment]
@sunshineywz123 I am sorry that we have not met this kind of issue before, would you mind sharing your outputs for testing

**Comment by hugoycj** [comment]
Propose closing temporarily unless there are new updates.
