### ISSUE TITLE
normal in  MuSHRoom_iphone-loftr

### ISSUE THREAD

**Issue by Binyr** [GAP-LAB-CUHK-SZ/gaustudio#74]
Hi, thanks for your great work!

I downloaded your dataset and found that there are normal in  "MuSHRoom_iphone-loftr". But the original MuSHRoom do not provide normal annotation. How do you get it!

Thank you,
Yanrui

**Comment by hugoycj** [comment]
We employ an early version of [StableNormal](https://github.com/Stable-X/StableNormal) for labeling. You could refer to this video https://www.youtube.com/watch?v=sylXTxG_U2U for comparision among different SOTA models  StableNormal (SIGGRAPH Asia 2024 (Journal Track)), GeoWizard (ECCV 2024), DSINE (CVPR 2024 Oral). "Our" in below figure and the video refers to StableNormal. 

<img width="1182" alt="image" src="https://github.com/user-attachments/assets/bad22967-b5d4-48c9-b1fa-6206c6b6c1f0">
<img width="1157" alt="image" src="https://github.com/user-attachments/assets/3c298da1-a54c-4c96-b8ed-d20e28399716">
<img width="1145" alt="image" src="https://github.com/user-attachments/assets/89bb8396-3b1e-4102-9cf9-3141c55c1c27">
<img width="1137" alt="image" src="https://github.com/user-attachments/assets/f1789e33-6fc5-44dc-aac8-65ac1fd042b3">
<img width="1144" alt="image" src="https://github.com/user-attachments/assets/f06fefc4-0cf5-4356-b1f5-f60a70414214">
