### ISSUE TITLE
High cost CPU RAM

### ISSUE THREAD

**Issue by yuyunlong2002** [GAP-LAB-CUHK-SZ/gaustudio#82]
I have encountered a problem here. When I extract mesh, the CPU RAM usage increases rapidly, causing the server to terminate the extraction. However, the GPU RAM utilization does not increase significantly, so I am not sure if it is a problem with my environment installation or if the system processing does require so much CPU RAM？

**Comment by hugoycj** [comment]
It is common when the voxel size is too small compared to your scene. You could refer to https://github.com/GAP-LAB-CUHK-SZ/gaustudio/issues/2 to tuning the voxel_size, image resolution, and space_carving

**Comment by yuyunlong2002** [comment]
Thank you for your amazing job and help, I solved this problem!
