### ISSUE TITLE
undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

### ISSUE THREAD

**Issue by ZhenWusi** [GAP-LAB-CUHK-SZ/gaustudio#9]
i use the following command to extract the mesh:

`gs-extract-mesh -m ./data/1750250955326095360_data/result -o ./output/1750250955326095360_data`

But the following errors will occur
<img width="636" alt="屏幕截图 2024-03-26 092548" src="https://github.com/GAP-LAB-CUHK-SZ/gaustudio/assets/105499590/99d8592d-2361-48c1-9a5a-fc1e3495bfd0">

when i run `pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118` later,my torch version change to 2.2.1,like this
<img width="529" alt="2" src="https://github.com/GAP-LAB-CUHK-SZ/gaustudio/assets/105499590/1dbeeac5-5879-477d-9a49-81270df7e86b">
and you requirements.txt don't have detail version

Can you help me?Thank you so much

**Comment by ZhenWusi** [comment]
I've fixed this issue and my cuda version is 11.8, so I just need to change the torch in the requirement.txt to torch == 2.0.1

**Comment by hugoycj** [comment]
Thanks for sharing that! I will update the requirements
